---
# set datetime that process began (for use in report)
- name: "Get datetime prior to update"
  shell: "date +'%Y-%m-%dT%H:%M:%SZ'"
  register: s_datetime

# perform update using underlying package manager
- name: "Perform update on all packages"
  package:
    name: '*'
    state: latest
  register: update_details

# set datetime that process ended (for use in report)
- name: "Get timestamp for end of update"
  shell: "date +'%Y-%m-%dT%H:%M:%SZ'"
  register: e_datetime

# get the duration
- name: "Get duration of update process"
  set_fact:
    duration: "{{ e_datetime.stdout|to_datetime('%Y-%m-%dT%H:%M:%SZ') - s_datetime.stdout|to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"

# store our jinja2 formatted report in a variable
- name: "Render update report"
  set_fact:
    update_report: "{{ lookup('template', 'update_report.j2') }}"

# print report to console
- name: "Print debug information"
  debug:
    var: update_report

# print our update report
- name: "Print update report to file"
  template:
    src: "templates/update_report.j2"
    dest: /tmp/update_report.txt
    mode: 0755